### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hassan-alnator**
Fix Wrong Zeebe client method in readme file

### CODE REVIEW

**Review by jwulf — APPROVED** [review]
Thanks for this @hassan-alnator. 

It needs to be a pull request against the `alpha` branch. I've updated that. 

Also, it needs the commit message amended to pass commitlint. Please see the details in step 7 here: https://github.com/camunda/camunda-8-js-sdk/blob/alpha/CONTRIBUTING.md

Are you able to amend the commit message? It should be something like: `docs(repo): update README.md`

**Review by jwulf — CHANGES_REQUESTED** [review]
Could you please amend the commit message to `docs(repo): update README.md`

**Comment by jwulf** [comment]
Oops, you've committed the `.idea` directory. If you could add `.idea` to the repo's `.gitignore` and do `git rm --cached .idea` and commit, you'll take those file out of the commit _and_ the repo will be set up for you and anyone else using a JetBrains IDE, and that would be awesome.

**Comment by hassan-alnator** [comment]
> Oops, you've committed the `.idea` directory. If you could add `.idea` to the repo's `.gitignore` and do `git rm --cached .idea` and commit, you'll take those file out of the commit _and_ the repo will be set up for you and anyone else using a JetBrains IDE, and that would be awesome.
> 
> I appreciate you working on this with me. This is the first external contribution to the SDK, so it's greasing the groove for everyone who comes after.

Change Completed , More than happy to support a project that I love :semi

**Review by jwulf — APPROVED** [review]

**Comment by jwulf** [comment]
@hassan-alnator - could you please sign the Contributor License Agreement here: https://cla-assistant.io/camunda/camunda-8-js-sdk

**Pull request merged**
